import type { AdminStore } from "@fullparty/admin";
import type { UserDmRateLimiter } from "../dm/userDmRateLimiter.js";
import type { FullpartyApi } from "../fullparty/client.js";
import type { GuildRunReminderQueue } from "../guildAutomation/runReminderQueue.js";
import type { GuildRunRoleStore } from "../guildAutomation/runRoleStore.js";
import type { GuildMemberCacheScheduler } from "../guildMembership/memberCacheScheduler.js";
import type { GuildMemberCacheStore } from "../guildMembership/memberCacheStore.js";
import type { GuildSettingsStore } from "../guildSettings/store.js";
import type { SqliteGuildScheduleStore } from "../guildSchedule/store.js";
import type { FailureReporter } from "../health/failureReporter.js";
import type { Logger } from "../lib/logger.js";
import type { RuntimeLogBuffer } from "../lib/runtimeLogBuffer.js";
import type { LatestPayloadStore } from "../payloads/latestPayloadStore.js";

export type BotContext = {
  adminApiToken?: string | undefined;
  adminStore?: AdminStore | undefined;
  failureReporter?: FailureReporter | undefined;
  fullparty: FullpartyApi;
  fullpartyWebBaseUrl: string;
  guildMemberCache?: GuildMemberCacheStore | undefined;
  guildMemberCacheScheduler?: GuildMemberCacheScheduler | undefined;
  guildRunRoles?: GuildRunRoleStore | undefined;
  guildRunReminderQueue?: GuildRunReminderQueue | undefined;
  guildSettings: GuildSettingsStore;
  guildScheduleStore?: Pick<SqliteGuildScheduleStore, "get"> | undefined;
  logger: Logger;
  payloadCommandAllowedUserId?: string | undefined;
  payloads: LatestPayloadStore;
  runtimeLogs?: RuntimeLogBuffer | undefined;
  userDmRateLimiter?: UserDmRateLimiter | undefined;
};
